name: Build all firmwares

on:
  push:
    paths:
      - 'qmk_firmware/keyboards/keyball/**.mk'
      - 'qmk_firmware/keyboards/keyball/**.c'
      - 'qmk_firmware/keyboards/keyball/**.h'
      - 'qmk_firmware/keyboards/keyball/**.json'
      - '.github/**.yml'
    tags-ignore:
      - '*'
    branches:
      - '*'

  pull_request:
    paths:
      - 'qmk_firmware/keyboards/keyball/**.mk'
      - 'qmk_firmware/keyboards/keyball/**.c'
      - 'qmk_firmware/keyboards/keyball/**.h'
      - 'qmk_firmware/keyboards/keyball/**.json'
      - '.github/**.yml'

  workflow_call: {}

jobs:

  build:

    strategy:
      matrix:
        # 変更点1: keyball39 だけにする
        keyboard: [ keyball39 ]
        # 変更点2: 'kat0226' を追加。不要なら test や default は消してOK
        # (念のため via は比較用に残していますが、不要なら消しても良いです)
        keymap: [ via, kat0226 ]
        
        # 変更点3: keyball46用の include 設定はすべて削除しました

    uses: ./.github/workflows/build-firmware.yml
    with:
      qmk_version: '0.22.14'
      keyboard:    ${{ matrix.keyboard }}
      keymap:      ${{ matrix.keymap }}

  check-size:
    name: Check size
    runs-on: ubuntu-22.04
    needs:
    - build

    steps:

    - uses: actions/download-artifact@v6
      with:
        pattern: "*-firmware"
        merge-multiple: true

    - name: List size of firmwares
      run: |
        for f in *.hex ; do
          cut -c 2,3 $f | awk '{s+=strtonum("0x" $1)}END{printf "%5d/28672 (%2d%%, %5d bytes free) ",s,s*100/28672,28672-s}'
          echo $f
        done
